
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Scanner;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author karthik
 */
public class userlog extends javax.swing.JFrame {

    /**
     * Creates new form userlog
     */
    public userlog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setText("Welcome User");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, -1, -1));

        jButton2.setText("View Vehicle Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jButton3.setText("View Vehicle Service Details");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/15e339e55b1db4ad4e3adfd0f3f0ff2e.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        this.dispose();
  //      vsbc v=new vsbc();
    //    v.setVisible(true);
    Boolean found=false;
    String cname=JOptionPane.showInputDialog(this,"Enter Customer Name/ Phone number");
    String name="";
    String ph="";
    String vno="";
    String type="";
    String cno="";
    Scanner x;
    try{
        String f2 = "D:\\java\\NetBeansProjects\\fsproj\\vehicle.txt";
        FileReader fr = new FileReader(f2);
			BufferedReader br = new BufferedReader(fr);
			String line = br.readLine();
                        
			int p=0;
			String[] stringcontents= {};
                   	while (line != null) {
				stringcontents = line.split(";");
            name=stringcontents[0];
            ph=stringcontents[1];
            vno=stringcontents[2];
            type=stringcontents[3];
            cno=stringcontents[4];
            
            if((cname.equals(name))||cname.equals(ph)){
                found=true; break;}
            line = br.readLine(); 
        }
        if(found)
            JOptionPane.showMessageDialog(rootPane,"name: "+name+"\nPhone:"+ph+"\n vehicle No:"+vno+"\ntype:"+type+"\nChasis No:"+cno);
        else
            JOptionPane.showMessageDialog(rootPane,"Record not found","Error", JOptionPane.ERROR_MESSAGE);
    
    }
       
     catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Record not found","Error", JOptionPane.ERROR_MESSAGE);
        }

   
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       //  this.dispose();
        //vvc v=new vvc();
        //v.setVisible(true);
        Boolean found=false;
    String cname=JOptionPane.showInputDialog(this,"Enter customer name/ Phone Number");
    String name="";
    String ph="";
    String vno="";
    String date="";
    String t="";
    String amt="";
    String status="";
    String ds="";
    
    Scanner x;
    try{
        String f2 = "D:\\java\\NetBeansProjects\\fsproj\\service.txt";
        FileReader fr = new FileReader(f2);
			BufferedReader br = new BufferedReader(fr);
			String line = br.readLine();
                        
			int p=0;
			String[] stringcontents= {};
                   	while (line != null) {
				stringcontents = line.split(";");
            name=stringcontents[0];
            ph=stringcontents[1];
            vno=stringcontents[2];
            date=stringcontents[3];
            t=stringcontents[4];
            amt=stringcontents[5];
            status=stringcontents[6];
            ds=stringcontents[7];
            
            if(cname.equals(name)){
                found=true; break;}
            line = br.readLine(); 
        }
        if(found)
            JOptionPane.showMessageDialog(rootPane,"Name: "+name+"\nPhone:"+ph+"\n Vehicle No:"+vno+"\nDate of service:"+date+"\nType:"+t+"\nService Amount:"+amt+"\n Status :"+status+"\n Delivery Status:"+ds);
        else
            JOptionPane.showMessageDialog(rootPane,"Record not found,Details yet to be Uploaded","Error", JOptionPane.ERROR_MESSAGE);
    
    }
       
     catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Record not found","Error", JOptionPane.ERROR_MESSAGE);
        }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        login l=new login();
        l.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userlog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
